create table notes (
    id integer primary key generated by default as identity,
    title text not null,
    content text,
    created_time timestamptz default now() not null,
    folder_id integer references folders(id) on delete cascade
);